
const enums: any = {
    "4.0.3": {
        level:[
            {
                nome: "Level 1",
                capitulo: [
                    "Secure Software Development Lifecycle",
                    "Authentication Architecture",
                    "Access Control Architecture",
                    "Input and Output Architecture",
                    "Cryptographic Architecture",
                    "Errors, Logging and Auditing Architecture",
                    "Data Protection and Privacy Architecture",
                    "Communications Architecture",
                    "Malicious Software Architecture",
                    "Business Logic Architecture",
                    "Secure File Upload Architecture",
                    "Configuration Architecture",
                    "Password Security",
                    "General Authenticator Security",
                    "Authenticator Lifecycle",
                    "Credential Storage",
                    "Credential Recovery",
                    "Look-up Secret Verifier",
                    "Out of Band Verifier",
                    "One Time Verifier",
                    "Cryptographic Verifier",
                    "Service Authentication",
                    "Fundamental Session Management Security",
                    "Session Binding",
                    "Session Termination",
                    "Cookie-based Session Management",
                    "Token-based Session Management",
                    "Federated Re-authentication",
                    "Defenses Against Session Management Exploits",
                    "General Access Control Design",
                    "Operation Level Access Control",
                    "Other Access Control Considerations",
                    "Input Validation",
                    "Sanitization and Sandboxing",
                    "Output Encoding and Injection Prevention",
                    "Memory, String, and Unmanaged Code",
                    "Deserialization Prevention",
                    "Data Classification",
                    "Algorithms",
                    "Random Values",
                    "Secret Management",
                    "Log Content",
                    "Log Processing",
                    "Log Protection",
                    "Error Handling",
                    "General Data Protection",
                    "Client-side Data Protection",
                    "Sensitive Private Data",
                    "Client Communication Security",
                    "Server Communication Security",
                    "Code Integrity",
                    "Malicious Code Search",
                    "Application Integrity",
                    "Business Logic Security",
                    "File Upload",
                    "File Integrity",
                    "File Execution",
                    "File Storage",
                    "File Download",
                    "SSRF Protection",
                    "Generic Web Service Security",
                    "RESTful Web Service",
                    "SOAP Web Service",
                    "GraphQL",
                    "Build and Deploy",
                    "Dependency",
                    "Unintended Security Disclosure",
                    "HTTP Security Headers",
                    "HTTP Request Header Validation"
                ],
                secao: [
                    "Authentication Architecture",
                    "Secure Software Development Lifecycle",
                    "Access Control Architecture",
                    "Input and Output Architecture",
                    "Cryptographic Architecture",
                    "Errors, Logging and Auditing Architecture",
                    "Data Protection and Privacy Architecture",
                    "Communications Architecture",
                    "Malicious Software Architecture",
                    "Business Logic Architecture",
                    "Secure File Upload Architecture",
                    "Configuration Architecture",
                    "Password Security",
                    "General Authenticator Security",
                    "Authenticator Lifecycle",
                    "Credential Storage",
                    "Credential Recovery",
                    "Look-up Secret Verifier",
                    "Out of Band Verifier",
                    "One Time Verifier",
                    "Cryptographic Verifier",
                    "Service Authentication",
                    "Fundamental Session Management Security",
                    "Session Binding",
                    "Session Termination",
                    "Cookie-based Session Management",
                    "Token-based Session Management",
                    "Federated Re-authentication",
                    "Defenses Against Session Management Exploits",
                    "General Access Control Design",
                    "Operation Level Access Control",
                    "Other Access Control Considerations",
                    "Input Validation",
                    "Sanitization and Sandboxing",
                    "Output Encoding and Injection Prevention",
                    "Memory, String, and Unmanaged Code",
                    "Deserialization Prevention",
                    "Data Classification",
                    "Algorithms",
                    "Random Values",
                    "Secret Management",
                    "Log Content",
                    "Log Processing",
                    "Log Protection",
                    "Error Handling",
                    "General Data Protection",
                    "Client-side Data Protection",
                    "Sensitive Private Data",
                    "Client Communication Security",
                    "Server Communication Security",
                    "Code Integrity",
                    "Malicious Code Search",
                    "Application Integrity",
                    "Business Logic Security",
                    "File Upload",
                    "File Integrity",
                    "File Execution",
                    "File Storage",
                    "File Download",
                    "SSRF Protection",
                    "Generic Web Service Security",
                    "RESTful Web Service",
                    "SOAP Web Service",
                    "GraphQL",
                    "Build and Deploy",
                    "Dependency",
                    "Unintended Security Disclosure",
                    "HTTP Security Headers",
                    "HTTP Request Header Validation"
                ]
            },
            {
                nome: "Level 2",
                capitulo: [
                    "Secure Software Development Lifecycle",
                    "Authentication Architecture",
                    "Access Control Architecture",
                    "Input and Output Architecture",
                    "Cryptographic Architecture",
                    "Errors, Logging and Auditing Architecture",
                    "Data Protection and Privacy Architecture",
                    "Communications Architecture",
                    "Malicious Software Architecture",
                    "Business Logic Architecture",
                    "Secure File Upload Architecture",
                    "Configuration Architecture",
                    "Password Security",
                    "General Authenticator Security",
                    "Authenticator Lifecycle",
                    "Credential Storage",
                    "Credential Recovery",
                    "Look-up Secret Verifier",
                    "Out of Band Verifier",
                    "One Time Verifier",
                    "Cryptographic Verifier",
                    "Service Authentication",
                    "Fundamental Session Management Security",
                    "Session Binding",
                    "Session Termination",
                    "Cookie-based Session Management",
                    "Token-based Session Management",
                    "Federated Re-authentication",
                    "Defenses Against Session Management Exploits",
                    "General Access Control Design",
                    "Operation Level Access Control",
                    "Other Access Control Considerations",
                    "Input Validation",
                    "Sanitization and Sandboxing",
                    "Output Encoding and Injection Prevention",
                    "Memory, String, and Unmanaged Code",
                    "Deserialization Prevention",
                    "Data Classification",
                    "Algorithms",
                    "Random Values",
                    "Secret Management",
                    "Log Content",
                    "Log Processing",
                    "Log Protection",
                    "Error Handling",
                    "General Data Protection",
                    "Client-side Data Protection",
                    "Sensitive Private Data",
                    "Client Communication Security",
                    "Server Communication Security",
                    "Code Integrity",
                    "Malicious Code Search",
                    "Application Integrity",
                    "Business Logic Security",
                    "File Upload",
                    "File Integrity",
                    "File Execution",
                    "File Storage",
                    "File Download",
                    "SSRF Protection",
                    "Generic Web Service Security",
                    "RESTful Web Service",
                    "SOAP Web Service",
                    "GraphQL",
                    "Build and Deploy",
                    "Dependency",
                    "Unintended Security Disclosure",
                    "HTTP Security Headers",
                    "HTTP Request Header Validation"
                ],
                secao: [
                    "Authentication Architecture",
                    "Secure Software Development Lifecycle",
                    "Access Control Architecture",
                    "Input and Output Architecture",
                    "Cryptographic Architecture",
                    "Errors, Logging and Auditing Architecture",
                    "Data Protection and Privacy Architecture",
                    "Communications Architecture",
                    "Malicious Software Architecture",
                    "Business Logic Architecture",
                    "Secure File Upload Architecture",
                    "Configuration Architecture",
                    "Password Security",
                    "General Authenticator Security",
                    "Authenticator Lifecycle",
                    "Credential Storage",
                    "Credential Recovery",
                    "Look-up Secret Verifier",
                    "Out of Band Verifier",
                    "One Time Verifier",
                    "Cryptographic Verifier",
                    "Service Authentication",
                    "Fundamental Session Management Security",
                    "Session Binding",
                    "Session Termination",
                    "Cookie-based Session Management",
                    "Token-based Session Management",
                    "Federated Re-authentication",
                    "Defenses Against Session Management Exploits",
                    "General Access Control Design",
                    "Operation Level Access Control",
                    "Other Access Control Considerations",
                    "Input Validation",
                    "Sanitization and Sandboxing",
                    "Output Encoding and Injection Prevention",
                    "Memory, String, and Unmanaged Code",
                    "Deserialization Prevention",
                    "Data Classification",
                    "Algorithms",
                    "Random Values",
                    "Secret Management",
                    "Log Content",
                    "Log Processing",
                    "Log Protection",
                    "Error Handling",
                    "General Data Protection",
                    "Client-side Data Protection",
                    "Sensitive Private Data",
                    "Client Communication Security",
                    "Server Communication Security",
                    "Code Integrity",
                    "Malicious Code Search",
                    "Application Integrity",
                    "Business Logic Security",
                    "File Upload",
                    "File Integrity",
                    "File Execution",
                    "File Storage",
                    "File Download",
                    "SSRF Protection",
                    "Generic Web Service Security",
                    "RESTful Web Service",
                    "SOAP Web Service",
                    "GraphQL",
                    "Build and Deploy",
                    "Dependency",
                    "Unintended Security Disclosure",
                    "HTTP Security Headers",
                    "HTTP Request Header Validation"
                ]
            },
            {
                nome: "Level 3",
                capitulo: [
                    "Secure Software Development Lifecycle",
                    "Authentication Architecture",
                    "Access Control Architecture",
                    "Input and Output Architecture",
                    "Cryptographic Architecture",
                    "Errors, Logging and Auditing Architecture",
                    "Data Protection and Privacy Architecture",
                    "Communications Architecture",
                    "Malicious Software Architecture",
                    "Business Logic Architecture",
                    "Secure File Upload Architecture",
                    "Configuration Architecture",
                    "Password Security",
                    "General Authenticator Security",
                    "Authenticator Lifecycle",
                    "Credential Storage",
                    "Credential Recovery",
                    "Look-up Secret Verifier",
                    "Out of Band Verifier",
                    "One Time Verifier",
                    "Cryptographic Verifier",
                    "Service Authentication",
                    "Fundamental Session Management Security",
                    "Session Binding",
                    "Session Termination",
                    "Cookie-based Session Management",
                    "Token-based Session Management",
                    "Federated Re-authentication",
                    "Defenses Against Session Management Exploits",
                    "General Access Control Design",
                    "Operation Level Access Control",
                    "Other Access Control Considerations",
                    "Input Validation",
                    "Sanitization and Sandboxing",
                    "Output Encoding and Injection Prevention",
                    "Memory, String, and Unmanaged Code",
                    "Deserialization Prevention",
                    "Data Classification",
                    "Algorithms",
                    "Random Values",
                    "Secret Management",
                    "Log Content",
                    "Log Processing",
                    "Log Protection",
                    "Error Handling",
                    "General Data Protection",
                    "Client-side Data Protection",
                    "Sensitive Private Data",
                    "Client Communication Security",
                    "Server Communication Security",
                    "Code Integrity",
                    "Malicious Code Search",
                    "Application Integrity",
                    "Business Logic Security",
                    "File Upload",
                    "File Integrity",
                    "File Execution",
                    "File Storage",
                    "File Download",
                    "SSRF Protection",
                    "Generic Web Service Security",
                    "RESTful Web Service",
                    "SOAP Web Service",
                    "GraphQL",
                    "Build and Deploy",
                    "Dependency",
                    "Unintended Security Disclosure",
                    "HTTP Security Headers",
                    "HTTP Request Header Validation"
                ],
                secao: [
                    "Authentication Architecture",
                    "Secure Software Development Lifecycle",
                    "Access Control Architecture",
                    "Input and Output Architecture",
                    "Cryptographic Architecture",
                    "Errors, Logging and Auditing Architecture",
                    "Data Protection and Privacy Architecture",
                    "Communications Architecture",
                    "Malicious Software Architecture",
                    "Business Logic Architecture",
                    "Secure File Upload Architecture",
                    "Configuration Architecture",
                    "Password Security",
                    "General Authenticator Security",
                    "Authenticator Lifecycle",
                    "Credential Storage",
                    "Credential Recovery",
                    "Look-up Secret Verifier",
                    "Out of Band Verifier",
                    "One Time Verifier",
                    "Cryptographic Verifier",
                    "Service Authentication",
                    "Fundamental Session Management Security",
                    "Session Binding",
                    "Session Termination",
                    "Cookie-based Session Management",
                    "Token-based Session Management",
                    "Federated Re-authentication",
                    "Defenses Against Session Management Exploits",
                    "General Access Control Design",
                    "Operation Level Access Control",
                    "Other Access Control Considerations",
                    "Input Validation",
                    "Sanitization and Sandboxing",
                    "Output Encoding and Injection Prevention",
                    "Memory, String, and Unmanaged Code",
                    "Deserialization Prevention",
                    "Data Classification",
                    "Algorithms",
                    "Random Values",
                    "Secret Management",
                    "Log Content",
                    "Log Processing",
                    "Log Protection",
                    "Error Handling",
                    "General Data Protection",
                    "Client-side Data Protection",
                    "Sensitive Private Data",
                    "Client Communication Security",
                    "Server Communication Security",
                    "Code Integrity",
                    "Malicious Code Search",
                    "Application Integrity",
                    "Business Logic Security",
                    "File Upload",
                    "File Integrity",
                    "File Execution",
                    "File Storage",
                    "File Download",
                    "SSRF Protection",
                    "Generic Web Service Security",
                    "RESTful Web Service",
                    "SOAP Web Service",
                    "GraphQL",
                    "Build and Deploy",
                    "Dependency",
                    "Unintended Security Disclosure",
                    "HTTP Security Headers",
                    "HTTP Request Header Validation"
                ]
            }
        ],
    }
}

export default enums;